export const INIT_AUTHSTATE="INIT_AUTHSTATE";
export const LOADING_CHNG="LOADING_CHNG";
export const CNG_CURRENT_GROUP="CNG_CURRENT_GROUP";

export const ON_EDIT_USER = "ON_EDIT_USER";

export const ON_CREATE_CONNECTION = "ON_CREATE_CONNECTION";

export const TOGGLE_CONNECTION = "TOGGLE_CONNECTION";
export const CHAT_CONNECTION="CHAT_CONNECTION";

export const AUTH_SUCCESS ="AUTH_SUCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_START = "AUTH_START";

export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTH_LOGOUT="AUTH_LOGOUT";

export const REALTIME_GROUP_UPDATE = "REALTIME_GROUP_UPDATE";
export const REALTIME_USER_GROUP = "REALTIME_USER_GROUP";

export const NEWCHAT_ADDED="NEWCHAT_ADDED";
export const NEWCHAT_ADD_FAIL="NEWCHAT_ADD_FAIL";

export const FORWARD_MESSAGE_ADDED="FORWARD_MESSAGE_ADDED";
export const FORWARD_MESSAGE_ADD_FAIL="FORWARD_MESSAGE_ADD_FAIL";

export const CHANGE_CURRENT_MSG="CHANGE_CURRENT_MSG";

export const GET_REALTIME_CONVERSATIONS_SUC="GET_REALTIME_CONVERSATIONS_SUC";
export const GET_REALTIME_CONVERSATIONS_FAIL="GET_REALTIME_CONVERSATIONS_FAIL";

export const GET_REALTIME_CHAT_SUC="GET_REALTIME_CHAT_SUC";
export const GET_REALTIME_CHAT_FAIL="GET_REALTIME_CHAT_FAIL";

export const GET_REALTIME_USER_SUC="GET_REALTIME_USER_SUC";
export const GET_REALTIME_USER_FAIL="GET_REALTIME_USER_FAIL";

export const DELETED_MSG="DELETED_MSG";

export const GET_CURRENT_GROUPDATA="GET_CURRENT_GROUPDATA";

export const ON_BLOCK_USER="ON_BLOCK_USER";
export const ON_UNBLOCK_USER="ON_UNBLOCK_USER";

export const ON_UNSUBSCRIBE="ON_UNSUBSCRIBE";